import * as vscode from 'vscode';
import { TraceRecord } from 'prompttrace';
import { Integration } from '../integration';
import { StateManager } from '../state';
import { detectPatterns } from '../pattern-detector';
import { generateSuggestions } from '../suggestions';
import { InlineFeedback } from './inline-feedback';

export class PrompttraceWebviewProvider implements vscode.WebviewViewProvider {
  public static readonly viewType = 'prompttrace.panel';
  private _view?: vscode.WebviewView;

  constructor(
    private readonly extensionUri: vscode.Uri,
    private readonly integration: Integration,
    private readonly state: StateManager,
    private readonly inlineFeedback?: InlineFeedback
  ) {}

  resolveWebviewView(
    webviewView: vscode.WebviewView,
    _context: vscode.WebviewViewResolveContext,
    _token: vscode.CancellationToken
  ): void {
    this._view = webviewView;
    webviewView.webview.options = { enableScripts: true };
    this.refresh();

    webviewView.webview.onDidReceiveMessage((msg) => {
      if (msg.command === 'refresh') {
        this.refresh();
      } else if (msg.command === 'optimize' && msg.traceId) {
        const traces = this.integration.getAllTraces();
        const trace = traces.find((t) => t.id === msg.traceId);
        if (trace) {
          const { diff } = this.integration.optimizeTrace(trace);
          const pct = diff.originalTokens > 0 ? Math.round((diff.diffTokens / diff.originalTokens) * 100) : 0;
          vscode.window.showInformationMessage(
            `✅ Saved ${diff.diffTokens} tokens (${pct}%) | -$${diff.projectedMonthlySavings.toFixed(2)}/mo`
          );
        }
      } else if (msg.command === 'copyOptimized' && msg.traceId) {
        const traces = this.integration.getAllTraces();
        const trace = traces.find((t) => t.id === msg.traceId);
        if (trace) {
          const { optimized } = this.integration.optimizeTrace(trace);
          const text = optimized.map((m) => `[${m.role}]\n${m.content}`).join('\n\n---\n\n');
          vscode.env.clipboard.writeText(text);
          vscode.window.showInformationMessage('✅ Optimized prompt copied!');
        }
      } else if (msg.command === 'copySnapshot') {
        this.copySessionSnapshot();
      }
    });
  }

  public refresh(): void {
    if (!this._view) return;
    const traces = this.integration.getAllTraces();
    this._view.webview.html = this.getHtml(traces);
  }

  private copySessionSnapshot(): void {
    const traces = this.integration.getAllTraces();
    const totalCost = traces.reduce((s, t) => s + t.cost, 0);
    const totalTokens = traces.reduce((s, t) => s + t.totalTokens, 0);
    const patterns = detectPatterns(traces);

    const lines = [
      `📊 Prompttrace Report`,
      `─────────────────────`,
      `Total Requests: ${traces.length}`,
      `Total Tokens: ${totalTokens.toLocaleString()}`,
      `Total Cost: $${totalCost.toFixed(4)}`,
      `Projected Monthly: $${(totalCost * 10000).toFixed(2)}`,
      '',
    ];

    if (patterns.topCostContributors.length > 0) {
      lines.push(`Top Cost Contributors:`);
      patterns.topCostContributors.slice(0, 3).forEach((p) => {
        lines.push(`  • ${p.label} → ${p.costPercent}% ($${p.totalCost.toFixed(4)})`);
      });
    }

    lines.push('', 'Generated by Prompttrace');

    vscode.env.clipboard.writeText(lines.join('\n'));
    vscode.window.showInformationMessage('📊 Session report copied!');
  }

  private getHtml(traces: TraceRecord[]): string {
    const sessionCost = this.state.getSessionCost();
    const sessionTokens = this.state.getSessionTokens();
    const sessionRequests = this.state.getSessionRequests();

    // Pre-send analysis stats
    const preSendStats = this.inlineFeedback?.getSessionStats() || { savedTokens: 0, analysisCount: 0 };

    const totalCost = traces.reduce((s, t) => s + t.cost, 0);
    const totalTokens = traces.reduce((s, t) => s + t.totalTokens, 0);
    const avgLatency = traces.length > 0 ? Math.round(traces.reduce((s, t) => s + t.latency, 0) / traces.length) : 0;

    // Pattern detection
    const patterns = detectPatterns(traces);

    // Cost breakdown HTML
    const costBreakdownHtml = patterns.topCostContributors.length > 0
      ? patterns.topCostContributors.map((p) => {
          const barWidth = Math.max(p.costPercent, 3);
          return `<div class="cost-bar-row">
            <div class="cost-bar-label">${p.label.slice(0, 30)}${p.label.length > 30 ? '...' : ''}</div>
            <div class="cost-bar-track">
              <div class="cost-bar-fill" style="width:${barWidth}%"></div>
            </div>
            <div class="cost-bar-pct">${p.costPercent}%</div>
          </div>`;
        }).join('')
      : '<div class="empty-small">Not enough data</div>';

    // Repeated pattern alerts
    const patternAlerts = [
      ...patterns.repeatedPrompts.filter((p) => p.count > 2).map((p) =>
        `<div class="pattern-alert">🔁 "${p.label.slice(0, 35)}..." sent <strong>${p.count} times</strong> — caching saves $${p.totalCost.toFixed(4)}</div>`
      ),
      ...patterns.repeatedSystemPrompts.filter((p) => p.count > 2).map((p) =>
        `<div class="pattern-alert">📋 Same system prompt used across <strong>${p.count} requests</strong> (${p.costPercent}% of cost)</div>`
      ),
    ].slice(0, 3).join('');

    // Smart suggestions for latest trace
    const latestTrace = traces[0];
    const suggestionsHtml = latestTrace
      ? generateSuggestions(latestTrace).slice(0, 4).map((s) =>
          `<div class="suggestion-row">
            <span class="sug-icon">${s.icon}</span>
            <div class="sug-body">
              <div class="sug-title">${s.title}</div>
              <div class="sug-desc">${s.description.slice(0, 100)}${s.description.length > 100 ? '...' : ''}</div>
              <div class="sug-savings">${s.savingsEstimate}</div>
            </div>
          </div>`
        ).join('')
      : '';

    // Trace rows
    const traceRows = traces.slice(0, 25).map((t) => {
      const hasHigh = t.insights.some((i) => i.severity >= 3);
      const hasMed = t.insights.some((i) => i.severity >= 2);
      const badge = hasHigh ? `<span class="badge critical">🔴</span>`
        : hasMed ? `<span class="badge warn">🟡</span>`
        : t.insights.length > 0 ? `<span class="badge info">🔵</span>`
        : `<span class="badge ok">✅</span>`;

      // Sort insights by severity (highest first)
      const sortedInsights = [...t.insights].sort((a, b) => b.severity - a.severity);

      const insightRows = sortedInsights.map((ins) =>
        `<div class="insight-row ${ins.severity >= 3 ? 'high' : ins.severity >= 2 ? 'med' : 'low'}">
          <span class="sev-icon">${ins.severity >= 3 ? '🔴' : ins.severity >= 2 ? '🟡' : '🔵'}</span>
          <span>${ins.message}</span>
        </div>`
      ).join('');

      const simRows = (t.impactSimulations || []).map((sim) =>
        `<div class="sim-row"><span>${sim.scenario}</span><span class="savings">-$${sim.projectedMonthlySavings.toFixed(2)}/mo</span></div>`
      ).join('');

      return `
        <details class="trace-card${hasHigh ? ' has-critical' : ''}">
          <summary>
            <div class="trace-header">
              <div class="trace-meta">
                <span class="model">${t.model}</span>
                ${badge}
              </div>
              <div class="trace-stats">
                <span>${t.totalTokens.toLocaleString()} tok</span>
                <span class="cost-val">$${t.cost.toFixed(5)}</span>
                <span>${t.latency}ms</span>
                <span class="timestamp">${new Date(t.timestamp).toLocaleTimeString()}</span>
              </div>
            </div>
          </summary>
          <div class="trace-body">
            <div class="metrics-row">
              <div class="metric"><span class="label">Input</span><span class="val">${t.inputTokens}</span></div>
              <div class="metric"><span class="label">Output</span><span class="val">${t.outputTokens}</span></div>
              <div class="metric"><span class="label">System</span><span class="val ${t.breakdown.systemTokens > 500 ? 'val-warn' : ''}">${t.breakdown.systemTokens}</span></div>
              <div class="metric"><span class="label">History</span><span class="val ${t.breakdown.historyTokens > 1000 ? 'val-warn' : ''}">${t.breakdown.historyTokens}</span></div>
              <div class="metric"><span class="label">User</span><span class="val">${t.breakdown.userTokens}</span></div>
            </div>
            ${t.cacheHits > 0 ? `<div class="cache-alert">🔁 Sent ${t.cacheHits + 1} times — cache to save <strong class="savings-text">100%</strong></div>` : ''}
            ${insightRows ? `<div class="insights-section"><h4>Diagnostics</h4>${insightRows}</div>` : ''}
            ${simRows ? `<div class="sim-section"><h4>💡 If You Fix This</h4>${simRows}</div>` : ''}
            <div class="action-row">
              <button class="optimize-btn" onclick="postMsg('optimize','${t.id}')">⚡ Optimize</button>
              <button class="copy-btn" onclick="postMsg('copyOptimized','${t.id}')">📋 Copy</button>
            </div>
          </div>
        </details>`;
    }).join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:var(--vscode-sideBar-background,#1e1e1e);color:var(--vscode-sideBar-foreground,#ccc);font-size:12px;padding:12px}

  .header{display:flex;align-items:center;gap:8px;margin-bottom:14px;padding-bottom:10px;border-bottom:1px solid var(--vscode-panel-border,#333)}
  .header h2{font-size:14px;font-weight:600}

  .session-banner{background:linear-gradient(135deg,rgba(245,158,11,0.12),rgba(239,68,68,0.08));border:1px solid rgba(245,158,11,0.25);border-radius:8px;padding:14px;margin-bottom:14px}
  .session-banner .session-title{font-size:10px;text-transform:uppercase;letter-spacing:.5px;opacity:.6;margin-bottom:6px}
  .session-stats{display:flex;gap:14px;align-items:baseline}
  .session-big{font-size:22px;font-weight:800;color:#f59e0b}
  .session-sub{font-size:11px;opacity:.5}

  .section-head{font-size:10px;text-transform:uppercase;letter-spacing:.6px;opacity:.45;margin:14px 0 8px;display:flex;align-items:center;gap:6px}

  /* Cost Breakdown Bars */
  .cost-bar-row{display:flex;align-items:center;gap:6px;margin-bottom:6px}
  .cost-bar-label{width:100px;font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;opacity:.7}
  .cost-bar-track{flex:1;height:6px;background:var(--vscode-panel-border,#333);border-radius:3px;overflow:hidden}
  .cost-bar-fill{height:100%;background:linear-gradient(90deg,#ef4444,#f59e0b);border-radius:3px;transition:width .3s ease}
  .cost-bar-pct{width:30px;text-align:right;font-size:10px;font-weight:700;color:#ef4444}

  /* Pattern Alerts */
  .pattern-alert{background:rgba(245,158,11,0.08);border:1px solid rgba(245,158,11,0.2);border-radius:6px;padding:8px;font-size:11px;margin-bottom:6px;line-height:1.4}
  .pattern-alert strong{color:#f59e0b}

  /* Suggestions */
  .suggestion-row{display:flex;gap:8px;padding:8px;background:var(--vscode-editor-background,#252526);border:1px solid var(--vscode-panel-border,#333);border-radius:6px;margin-bottom:6px}
  .sug-icon{font-size:16px;flex-shrink:0;margin-top:2px}
  .sug-body{flex:1}
  .sug-title{font-weight:600;font-size:12px;margin-bottom:3px}
  .sug-desc{font-size:10px;opacity:.6;line-height:1.3;margin-bottom:3px}
  .sug-savings{font-size:11px;color:#10b981;font-weight:600}

  /* Stats Grid */
  .stats-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-bottom:14px}
  .stat-card{background:var(--vscode-editor-background,#252526);border:1px solid var(--vscode-panel-border,#333);border-radius:6px;padding:10px}
  .stat-card .label{font-size:9px;text-transform:uppercase;opacity:.5;letter-spacing:.5px}
  .stat-card .value{font-size:15px;font-weight:700;margin-top:3px}
  .stat-card.pain{border-left:3px solid #ef4444}
  .stat-card.pain .value{color:#ef4444}

  /* Traces */
  .trace-card{background:var(--vscode-editor-background,#252526);border:1px solid var(--vscode-panel-border,#333);border-radius:6px;margin-bottom:5px;overflow:hidden;transition:border-color .15s}
  .trace-card.has-critical{border-left:3px solid #ef4444}
  .trace-card summary{cursor:pointer;padding:9px 11px;list-style:none}
  .trace-card summary::-webkit-details-marker{display:none}
  .trace-card[open]{border-color:#3b82f6}
  .trace-header{display:flex;flex-direction:column;gap:3px}
  .trace-meta{display:flex;align-items:center;justify-content:space-between}
  .model{font-weight:600;font-size:12px}
  .trace-stats{display:flex;gap:8px;font-size:11px;opacity:.7}
  .cost-val{color:#ef4444;font-weight:600}
  .timestamp{opacity:.4}
  .badge{font-size:10px;padding:1px 5px;border-radius:3px;font-weight:600}
  .badge.critical{background:rgba(239,68,68,.2);color:#ef4444}
  .badge.warn{background:rgba(245,158,11,.2);color:#f59e0b}
  .badge.info{background:rgba(59,130,246,.2);color:#60a5fa}
  .badge.ok{background:rgba(16,185,129,.2);color:#10b981}
  .trace-body{padding:10px;border-top:1px solid var(--vscode-panel-border,#333)}
  .metrics-row{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:8px}
  .metric{display:flex;flex-direction:column;align-items:center;background:var(--vscode-sideBar-background,#1e1e1e);padding:5px 8px;border-radius:4px;min-width:45px}
  .metric .label{font-size:8px;text-transform:uppercase;opacity:.45}
  .metric .val{font-size:12px;font-weight:600}
  .metric .val-warn{color:#f59e0b}
  .cache-alert{background:rgba(59,130,246,.08);border:1px solid rgba(59,130,246,.25);padding:7px;border-radius:4px;font-size:11px;margin-bottom:8px}
  .savings-text{color:#10b981}
  .insights-section,.sim-section{margin-bottom:8px}
  .insights-section h4,.sim-section h4{font-size:9px;text-transform:uppercase;opacity:.4;margin-bottom:5px;letter-spacing:.5px}
  .insight-row{padding:3px 0;font-size:11px;display:flex;align-items:flex-start;gap:5px;line-height:1.35}
  .sev-icon{flex-shrink:0;font-size:10px}
  .sim-row{display:flex;justify-content:space-between;align-items:center;padding:5px 7px;border-radius:4px;background:rgba(16,185,129,.06);margin-bottom:3px;font-size:11px}
  .savings{color:#10b981;font-weight:700;font-size:12px}
  .action-row{display:flex;gap:5px}
  .optimize-btn,.copy-btn{flex:1;padding:7px;border:none;border-radius:4px;cursor:pointer;font-size:11px;font-weight:600}
  .optimize-btn{background:var(--vscode-button-background,#0e639c);color:var(--vscode-button-foreground,#fff)}
  .copy-btn{background:var(--vscode-editor-background,#1e1e1e);color:var(--vscode-sideBar-foreground,#ccc);border:1px solid var(--vscode-panel-border,#333)}
  .optimize-btn:hover,.copy-btn:hover{opacity:.85}
  .refresh-btn,.share-btn{background:none;border:1px solid var(--vscode-panel-border,#333);color:var(--vscode-sideBar-foreground,#ccc);padding:4px 8px;border-radius:4px;cursor:pointer;font-size:10px}
  .empty{text-align:center;padding:30px 20px;opacity:.4}
  .empty-small{text-align:center;padding:8px;opacity:.3;font-size:10px}

  /* Pre-Send Analysis */
  .presend-banner{background:linear-gradient(135deg,rgba(59,130,246,0.08),rgba(16,185,129,0.06));border:1px solid rgba(59,130,246,0.2);border-radius:8px;padding:12px;margin-bottom:10px}
  .presend-stat{display:flex;justify-content:space-between;align-items:center;padding:4px 0}
  .presend-label{font-size:11px;opacity:.65}
  .presend-value{font-size:14px;font-weight:700;color:#3b82f6}
  .presend-green{color:#10b981}
</style>
</head>
<body>
  <div class="header">
    <h2>⚡ Prompttrace</h2>
    <div style="flex:1"></div>
    <button class="share-btn" onclick="postMsg('copySnapshot')">📊 Share</button>
    <button class="refresh-btn" onclick="postMsg('refresh')">↻</button>
  </div>

  <div class="session-banner">
    <div class="session-title">💸 This Session</div>
    <div class="session-stats">
      <span class="session-big">$${sessionCost.toFixed(4)}</span>
      <span class="session-sub">${sessionTokens.toLocaleString()} tok · ${sessionRequests} req</span>
    </div>
  </div>

  <div class="stats-grid">
    <div class="stat-card pain">
      <div class="label">Projected /mo</div>
      <div class="value">$${(totalCost * 10000).toFixed(2)}</div>
    </div>
    <div class="stat-card">
      <div class="label">All-Time</div>
      <div class="value">$${totalCost.toFixed(4)}</div>
    </div>
    <div class="stat-card">
      <div class="label">Tokens</div>
      <div class="value">${totalTokens.toLocaleString()}</div>
    </div>
    <div class="stat-card">
      <div class="label">Avg Latency</div>
      <div class="value">${avgLatency}ms</div>
    </div>
  </div>

  ${preSendStats.analysisCount > 0 ? `
  <div class="section-head">⚡ Pre-Send Analysis</div>
  <div class="presend-banner">
    <div class="presend-stat">
      <span class="presend-label">Prompts analyzed before sending</span>
      <span class="presend-value">${preSendStats.analysisCount}</span>
    </div>
    <div class="presend-stat">
      <span class="presend-label">Tokens saved (pre-send)</span>
      <span class="presend-value presend-green">${preSendStats.savedTokens.toLocaleString()}</span>
    </div>
  </div>` : `
  <div class="section-head">⚡ Pre-Send Analysis</div>
  <div class="presend-banner">
    <div class="empty-small">Type a prompt to see live analysis.<br>Cmd: "Prompttrace: Analyze Current Input"</div>
  </div>`}

  ${patternAlerts ? `<div class="section-head">🔍 Detected Patterns</div>${patternAlerts}` : ''}

  <div class="section-head">📊 Where Money Goes</div>
  ${costBreakdownHtml}

  ${suggestionsHtml ? `<div class="section-head">🧠 Smart Suggestions</div>${suggestionsHtml}` : ''}

  <div class="section-head">📋 Traces (${traces.length})</div>
  ${traces.length === 0 ? '<div class="empty">No traces yet. Run <code>Prompttrace: Run Mock</code>.</div>' : traceRows}

  <script>
    const vscode = acquireVsCodeApi();
    function postMsg(command, traceId) { vscode.postMessage({ command, traceId }); }
  </script>
</body>
</html>`;
  }
}
