export interface TraceMessage {
  role: string;
  content: string;
}

export interface TraceInsight {
  type: "warning" | "info" | "success";
  message: string;
  severity: number;
}

export interface TokenBreakdown {
  systemTokens: number;
  userTokens: number;
  historyTokens: number;
  outputTokens: number;
}

export interface ImpactSimulation {
  potentialSavingsTokens: number;
  potentialSavingsCost: number;
  projectedMonthlySavings: number;
  scenario: string;
}

export interface TraceRecord {
  id: string;
  model: string;
  messages: TraceMessage[];
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  cost: number;
  projectedMonthlyCost: number; // calculated as cost * 10000
  latency: number;
  timestamp: number;
  breakdown: TokenBreakdown;
  insights: TraceInsight[];
  impactSimulations: ImpactSimulation[];
  cacheHits: number;
  aiAnalysis?: string;
  /** Refined prompt generated by an LLM to save cost while keeping context */
  refinedPrompt?: {
    text: string;
    reasoning: string;
  };
  promptHash: string;
}

export interface PrompttraceConfig {
  log?: boolean;
  store?: "local" | "none";
  aiAnalysis?: boolean;
  /** Custom AI model to use for analysis (e.g. llama-3.1-8b-instant) */
  aiModel?: string;
  /** Custom API base URL for open-source model endpoints (e.g. Groq/Ollama) */
  aiApiBase?: string;
}

export interface DiffResult {
  originalTokens: number;
  newTokens: number;
  diffTokens: number;
  originalCost: number;
  newCost: number;
  diffCost: number;
  projectedMonthlySavings: number;
}
